### ISSUE TITLE
Latest @guardian/eslint-config-typescript is broken

### ISSUE THREAD

**Issue by AshCorr** [guardian/csnx#104]
**Describe the bug**

When using the latest eslint-config-typescript@v1.0.10 eslint throws this error when extending

![image](https://user-images.githubusercontent.com/21217225/190641452-c6dd0028-d32e-4dab-ab8c-8796f1fa32f1.png)

I think the issue is that for some reason the build process is putting files in the wrong folder. This is what the folder structure looks like in v1.0.9

![image](https://user-images.githubusercontent.com/21217225/190641966-724d0f5d-7400-47c9-8ff9-39f225e1af84.png)

But the .eslintrc.json ends up in a nested folder in v1.0.10

![image](https://user-images.githubusercontent.com/21217225/190642117-8c3ca134-3f30-483d-92a2-d8706d7c4627.png)

**To Reproduce**

1. Run `npm i --save-dev @guardian/ eslint-config-typescript`
2. Add `"extends": "@guardian/ eslint-config-typescript"` to your `.eslintrc.json` file
3. Run `eslint`

**Comment by sndrs** [comment]
fixed by #105
