### ISSUE TITLE
Missing plugin in @guardian/eslint-config-typescript

### ISSUE THREAD

**Issue by jimhunty** [guardian/csnx#1239]
**Describe the bug**

When trying to use `@guardian/eslint-config-typescript` v9.0.3 within Editions, we get the following error

```
ESLint couldn't find the config "plugin:@typescript-eslint/recommended-type-checked" to extend from. Please check that the name of the config is correct.
```

This is because the eslint plugin is not part of the `package.json`

**To Reproduce**

Install the package on a clean project, run it and see the error

**Environment (please complete the following information):**

- Version 9.0.3 of the package.

**Comment by sndrs** [comment]
Thanks for raising this @jimhunty.

I'm afraid I'm unable to recreate it. 

`@guardian/eslint-config-typescript` has a dependency on `@typescript-eslint/eslint-plugin` and that provides `recommended-type-checked`, so it _should_ be present.

Are you still having issues with it?

**Comment by sndrs** [comment]
unable to reproduce
