### ISSUE TITLE
Update `@csnx/npm-package` to publish with new package.json exports

### ISSUE THREAD

**Issue by ashishpuliyel** [guardian/csnx#124]
- [ ] https://github.com/guardian/csnx/issues/123
- [x] use nrwl's rollup executor
- [x] set exports correctly (https://github.com/guardian/csnx/pull/114)
- [ ] target ES2020 for cjs (https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-14)

**Comment by sndrs** [comment]
- [ ] use nrwl's rollup executor
- [ ] set exports correctly
