### ISSUE TITLE
Bug in changesets creates more versions than we expect: https://github.com/changesets/changesets/pull/967

### ISSUE THREAD

**Issue by sndrs** [guardian/csnx#134]
Whenever we release a version of `@guardian/libs`, `@csnx/npm-package` gets versioned too because it depends on it (a changelog is generated and `version` is set to undefined).

This is added to the release PR too.

If you set `ignore` to include `@csnx/*` in the changesets config, it errors because it can't find a package to ignore. This is because we don't build `@csnx/npm-package`, and rewrite the pnpm workspace to publish from `dist`, as it's the customary location for builds in Nx.

this should be fixed by https://github.com/changesets/changesets/pull/967.

## Expected behavior
Releasing new versions of packages should not version internal, unpublished packages that depend on them.

**Comment by sndrs** [comment]
confirm this is still live

**Comment by SiAdcock** [comment]
If this resurfaces, we will fix it
