### ISSUE TITLE
Automate config generation

### ISSUE THREAD

**Issue by sndrs** [guardian/csnx#205]
we need config to handle multiple things, e.g. (non-exhaustive list i'm sure):

- [`.github/labeler.yml`](https://github.com/guardian/csnx/blob/main/.github/labeler.yml)
- [`.github/renovate.json5`](https://github.com/guardian/csnx/blob/main/.github/renovate.json5)

we should use scripts to keep these up-to-date, like with we do with the readme.

for example, the list of packages in `.github/labeler.yml` should match the public packages in the repo.

if we script these once, we don't have to worry about keeping them up to date.

**Comment by joecowton1** [comment]
Archiving until required.
