### ISSUE TITLE
Fix radio quiz answers in Source

### ISSUE THREAD

**Issue by sndrs** [guardian/csnx#256]
We've caught an issue with the quiz atoms where the label is no longer full width. 

Its a bigger issue than it looks as Atoms-Rendering is overriding the source styles quite significantly.

This issue should be resolved ideally in Source, but failing that in Atoms-Rendering.

![Image](https://user-images.githubusercontent.com/77005274/203059150-4e8f9fe0-c1d5-4fb9-ab3a-5f6ca3ba200e.png)

**Comment by sndrs** [comment]
we're not sure if this is still a live issue, if it is we can recreate it

**Comment by mxdvl** [comment]
This looks fine on the [last Thursday Quiz](https://www.theguardian.com/lifeandstyle/2024/mar/21/guardian-thursday-quiz-general-knowledge-topical-news-trivia-152)
