### ISSUE TITLE
Update / add icons in source

### ISSUE THREAD

**Issue by ashishpuliyel** [guardian/csnx#408]
Updating icons

Changes are;

1) Replace the existing edit icon with the new icon.
2) Remove the existing share-callout icon.
3) Add three new social icons. (telegram-brand, whats-app-brand, and signal-brand)

**Comment by ashishpuliyel** [comment]
When this is picked up, please speak to Akemi for more detail.

**Comment by akemitakagi** [comment]
New Edit icon

![Image](https://user-images.githubusercontent.com/5967941/216979844-33ad2fa1-2845-462a-9285-a0a25f8b0bdc.png)

Telegram, WhatsApp and Signal icons

![Image](https://user-images.githubusercontent.com/5967941/216980121-72d82719-c7de-4271-8fd1-3ff8d7ac9708.png)

The Telegram and WhatsApp icons are two colours, so the retainFill option maybe needs to be checked.

Please send me the chromatic page when they are done.

Figma file:
https://www.figma.com/file/Ai7AELHC6KCz38qKZkvuHo/%E2%97%90-Icons?node-id=2810%3A6938&t=lfz4sKQT0nsiPVK8-1

Thank you!
