### ISSUE TITLE
TS errors in unrelated projects in CSNX

### ISSUE THREAD

**Issue by joecowton1** [guardian/csnx#492]
From chat thread by Alex Sanders.

The issue seems to arise when:
- you build a project that is not configured to handle JSX 
- Nx doesn't have a cache result for that project (or you skip the cache)
- something in dist has a .d.ts that imports from @guardian/react-components (i.e. dev kitchen)

if you remove all import [whatevers] from "@guardian/source-react-components"; from dist/**/*.d.ts then everything seems fine

TS has found a declaration file that imports from a package that the paths config resolves to the react components source directory, and because the project is not set up handle jsx, it errors

what i don't know is why TS is worried about declaration files in `dist` at any point, let alone when building an unrelated project

for anyone else who looks into this, i reckon https://www.typescriptlang.org/tsconfig#Compiler_Diagnostics_6251 is your friend

**Comment by sndrs** [comment]
i guess it needs to be fixed? i reckon there's some interesting discoveries awaiting but they're very hard to spot right now
